### ISSUE TITLE
Using local credentials doesn't work

### ISSUE THREAD

**Issue by ghost** [ThijsRay/podimo#50]
When I'm using credentials provided via environment variables, the generated URL doenst work. When I the URL with username & password embedded, the URL works.

The compose file I use:
```
services:
  podimo:
    environment:
      - PODIMO_BIND_HOST=0.0.0.0:12104
      - PODIMO_PROTOCOL=https
      - PODIMO_HOSTNAME=podimo.host.tld
    volumes:
      - /mnt/ssd0/docker/data/podimo/cache:/src/cache
    image: ghcr.io/thijsray/podimo:latest
    restart: unless-stopped
```
Or with the local credentials
```
services:
  podimo:
    environment:
      - PODIMO_BIND_HOST=0.0.0.0:12104
      - PODIMO_PROTOCOL=https
      - LOCAL_CREDENTIALS=true
      - PODIMO_HOSTNAME=podimo.host.tld
      - PODIMO_EMAIL="myemailaddress"
      - PODIMO_PASSWORD="mypassword"
    volumes:
      - /mnt/ssd0/docker/data/podimo/cache:/src/cache
    image: ghcr.io/thijsray/podimo:latest
    restart: unless-stopped
```

Tried with & without " around e-mail / password.

**Comment by zarakkas** [comment]
Hi. I'm late to the party, but for me it helped to quote the `LOCAL_CREDENTIALS` option.

```
    environment:
      LOCAL_CREDENTIALS: "true"
      PODIMO_EMAIL: "myemailaddress"
      PODIMO_PASSWORD: "mypassword"
```
